services:
  backend:
    image: saivishwas11/ds-bot-backend:latest
    container_name: data-science-bot-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: saivishwas11/ds-bot-frontend:latest
    container_name: data-science-bot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
